import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Navbar
    dashboard: 'Dashboard',
    reportIssue: 'Report Issue',
    mapView: 'Map View',
    logout: 'Logout',
    signIn: 'Sign In',
    citizen: 'Citizen',
    officer: 'Officer',
    admin: 'Admin',

    // Landing
    heroTag: 'AI-Powered · Multilingual · Real-time',
    heroTitle1: 'Your City.',
    heroTitle2: 'Your Voice.',
    heroTitle3: 'Real Action.',
    heroDesc: 'Report civic issues in your language. AI automatically classifies and routes them to the right department. Track resolution in real time.',
    reportAnIssue: 'Report an Issue',
    viewComplaintsMap: 'View Complaints Map',
    issuesReported: 'Issues Reported',
    resolved: 'Resolved',
    cities: 'Cities',
    languages: 'Languages',
    citizenPortal: 'Citizen Portal',
    citizenPortalDesc: 'Report issues, track status, vote on complaints, and get AI voice assistance.',
    enterPortal: 'Enter Portal',
    officerDashboard: 'Officer Dashboard',
    officerDashboardDesc: 'View assigned complaints, update status, and manage resolutions efficiently.',
    officerLogin: 'Officer Login',
    adminPanel: 'Admin Panel',
    adminPanelDesc: 'Manage departments, officers, SLAs, and view comprehensive analytics.',
    adminLogin: 'Admin Login',
    poweredByAI: 'Powered by AI. Designed for Citizens.',
    voiceReporting: 'Voice Reporting',
    voiceReportingDesc: 'Report issues using your voice in any language',
    interactiveMap: 'Interactive Map',
    interactiveMapDesc: 'View all complaints on a live map',
    aiClassification: 'AI Classification',
    aiClassificationDesc: 'Automatic routing to right department',
    duplicateDetection: 'Duplicate Detection',
    duplicateDetectionDesc: 'Smart detection prevents repeat reports',
    realTimeTracking: 'Real-time Tracking',
    realTimeTrackingDesc: 'Track your complaint status live',
    anonymousMode: 'Anonymous Mode',
    anonymousModeDesc: 'Report without revealing your identity',
    footerText: '© 2025 CivicVoice — AI-Based Multilingual Civic Issue Reporting Platform',

    // Citizen Dashboard
    welcomeBack: 'Welcome',
    trackManage: 'Track and manage civic issues in your area',
    totalIssues: 'Total Issues',
    pending: 'Pending',
    inProgress: 'In Progress',
    resolvedStat: 'Resolved',
    newReport: 'New Report',
    voiceReport: 'Voice Report',
    nearbyIssues: 'Nearby Issues',
    recentComplaints: 'Recent Complaints',
    all: 'All',
    loadingComplaints: 'Loading complaints...',
    noComplaintsFound: 'No complaints found',
    beFirstToReport: 'Be the first to report an issue →',

    // Report Issue
    reportACivicIssue: 'Report a Civic Issue',
    helpImprove: 'Help improve your community by reporting issues',
    issueDetails: 'Issue Details',
    issueTitle: 'Issue Title',
    issueTitlePlaceholder: 'e.g., Large pothole on main street near bus stop',
    description: 'Description',
    descriptionPlaceholder: 'Describe the issue in detail. You can also use voice input in your language.',
    severityLevel: 'Severity Level',
    language: 'Language',
    reportAnonymously: 'Report Anonymously',
    reportAnonymouslyDesc: '— your identity will be hidden publicly',
    location: 'Location',
    locationDesc: 'Click on the map to pin the exact location of the issue',
    uploadImages: 'Upload Images',
    clickToUpload: 'Click to upload photos',
    uploadFormats: 'JPG, PNG up to 10MB each',
    submitReport: '📤 Submit Report',
    submitting: 'Submitting...',
    cancel: 'Cancel',
    stop: 'Stop',
    voiceInput: 'Voice Input',
    listening: 'Listening... speak now',

    // Map
    complaintsMap: 'Complaints Map',
    filterByStatus: 'Filter by Status',
    colorBy: 'Color by',
    category: 'category',
    status: 'status',
    show1kmRadius: 'Show 1km radius',
    legend: 'Legend',
    complaintsShown: 'complaints shown',
    recentIssues: 'Recent Issues',
    loadingMap: 'Loading map...',
    signInToReport: 'Sign In to Report',

    // Complaint Detail
    complaintDetails: 'Complaint Details',
    back: '← Back',
    support: 'Support',
    readAloud: '🔊 Read Aloud',
    readAloudStop: '⏹️ Stop',
    issuePhotos: 'Issue Photos',
    resolutionNote: '✅ Resolution Note',
    resolvedOn: 'Resolved on',
    locationLabel: '📍 Location',
    statusTimeline: 'Status Timeline',
    assignedOfficer: 'Assigned Officer',
    issueInfo: 'Issue Info',
    reportedBy: 'Reported By',
    priority: 'Priority',
    reportedOn: 'Reported On',
    slaDeadline: 'SLA Deadline',
    naLabel: 'N/A',
    anonymous: 'Anonymous',
    yes: 'Yes',
    no: 'No',
    severity: 'Severity',
    votes: 'Votes',
    department: 'Department',
    complaintNotFound: 'Complaint Not Found',
    backToDashboard: 'Back to Dashboard',

    // Officer Dashboard
    officerDashboardTitle: 'Officer Dashboard',
    assignedComplaints: 'Assigned Complaints',
    totalAssigned: 'Total Assigned',
    update: 'Update',
    updateComplaint: 'Update Complaint',
    updateStatus: 'Update Status',
    resolutionNoteLabel: 'Resolution Note',
    resolutionNotePlaceholder: 'Describe what action was taken...',
    resolutionImages: 'Resolution Images',
    uploadBeforeAfter: '📷 Upload before/after photos',
    updateStatusBtn: '✅ Update Status',
    updating: 'Updating...',
    noComplaintsAssigned: 'No complaints assigned yet',
    slaBreached: 'SLA Breached',
    hoursLeft: 'h left',

    // Admin Dashboard
    adminPanelTitle: 'Admin Panel',
    manageEntire: 'Manage the entire CivicVoice platform',
    analytics: 'Analytics',
    complaints: 'Complaints',
    officers: 'Officers',
    departments: 'Departments',
    citizens: 'Citizens',
    slaRules: 'SLA Rules',
    totalComplaints: 'Total Complaints',
    resolutionRate: 'Resolution Rate',
    slaBreaches: 'SLA Breaches',
    complaintsPassDeadline: 'Complaints past deadline',
    allOnTrack: 'All on track!',
    platformUsers: 'Platform Users',
    categoryBreakdown: 'Category Breakdown',
    topOfficers: 'Top Officers',
    noDataYet: 'No data yet',
    addOfficer: '+ Add Officer',
    addDepartment: '+ Add Department',
    seedDefaults: '🌱 Seed Defaults',
    deleteOfficer: 'Delete officer?',
    allComplaints: 'All Complaints',
    assignLabel: 'Assign...',
    title: 'Title',
    date: 'Date',
    assign: 'Assign',
    name: 'Name',
    email: 'Email',
    joined: 'Joined',
    statusLabel: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    noCitizensYet: 'No citizens registered yet',
    noComplaintsYet: 'No complaints yet',
    noOfficersYet: 'No officers added yet',
    noOfficersForDept: 'No officers in this department',
    addFirstOfficer: 'Add First Officer',
    noDepartmentsYet: 'No departments configured',
    seedDefaultDepartments: 'Seed Default Departments',
    addNewOfficer: 'Add New Officer',
    fullName: 'Full Name',
    password: 'Password',
    selectDepartment: 'Select Department',
    jurisdictionArea: 'Jurisdiction / Area',
    adding: 'Adding...',
    departmentName: 'Department Name',
    departmentDescription: 'Description',
    keywords: 'Keywords (comma-separated)',
    highSLA: 'High SLA (hrs)',
    mediumSLA: 'Medium SLA (hrs)',
    lowSLA: 'Low SLA (hrs)',

    // SLA Rules
    slaRulesTitle: 'SLA Rules',
    slaRulesDesc: 'Set resolution deadlines per department, category and priority',
    addSlaRule: '+ Add SLA Rule',
    editSlaRule: 'Edit SLA Rule',
    selectCategory: 'Select Category',
    selectPriority: 'Select Priority',
    deadlineHours: 'Deadline (hours)',
    saveSlaRule: 'Save Rule',
    saving: 'Saving...',
    noSlaRules: 'No SLA rules configured yet',
    hours: 'hrs',
    high: 'High',
    medium: 'Medium',
    low: 'Low',

    // Auth
    citizenLogin: 'Citizen Login',
    citizenRegister: 'Register',
    officerLoginTitle: 'Officer Login',
    adminLoginTitle: 'Admin Login',
    emailAddress: 'Email Address',
    enterPassword: 'Password',
    signingIn: 'Signing in...',
    registering: 'Registering...',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    createAccount: 'Create Account',

    // Auth page — extended
    welcomeBackCitizen: 'Welcome back',
    citizenLoginSubtitle: 'Sign in to report and track civic issues',
    officerPortalTitle: 'Officer Portal',
    officerLoginSubtitle: 'Sign in to manage and resolve civic complaints',
    adminPortalTitle: 'Admin Panel',
    adminLoginSubtitle: 'System administration and analytics',
    createAccountTitle: 'Create account',
    citizenRegisterSubtitle: 'Join thousands making their city better',
    fullName: 'Full Name',
    fullNamePlaceholder: 'John Smith',
    emailPlaceholder: 'you@example.com',
    officerEmailLabel: 'Officer Email',
    officerEmailPlaceholder: 'officer@municipality.gov',
    adminEmailLabel: 'Admin Email',
    adminEmailPlaceholder: 'admin@municipality.gov',
    passwordPlaceholder: '••••••••',
    atLeast6Chars: 'At least 6 characters',
    confirmPassword: 'Confirm Password',
    signInBtn: 'Sign In',
    signInAsOfficer: 'Sign In as Officer',
    signInAsAdmin: 'Sign In as Admin',
    registerHere: 'Register here',
    signInLink: 'Sign in',
    creatingAccount: 'Creating account...',
    officerAdminPortal: 'Are you an officer or admin?',
    backToHome: '← Back to Home',
    demoCredentials: 'Demo',
    passwordsMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    citizenPortalOnly: 'This portal is for citizens only.',
    officerPortalOnly: 'This portal is for officers only.',
    adminPortalOnly: 'This portal is for administrators only.',
    loginFailed: 'Login failed',
    registrationFailed: 'Registration failed',
    deptName: 'Department Name',
    deptDescription: 'Description',
    maxHours: 'Max Hours',
    noDescription: 'No description',
    seedDepartments: '🌱 Seed Departments',

    // Duplicate modal
    similarIssueFound: 'Similar Issue Found!',
    similarIssueDesc: 'This issue already exists nearby. Would you like to support it instead of creating a duplicate?',
    supportThisIssue: '👍 Support This Issue',
    reportAnyway: 'Report Anyway',
  },

  hi: {
    // Navbar
    dashboard: 'डैशबोर्ड',
    reportIssue: 'समस्या रिपोर्ट करें',
    mapView: 'मानचित्र',
    logout: 'लॉग आउट',
    signIn: 'साइन इन',
    citizen: 'नागरिक',
    officer: 'अधिकारी',
    admin: 'व्यवस्थापक',

    // Landing
    heroTag: 'AI-संचालित · बहुभाषी · वास्तविक समय',
    heroTitle1: 'आपका शहर।',
    heroTitle2: 'आपकी आवाज़।',
    heroTitle3: 'असली कार्रवाई।',
    heroDesc: 'अपनी भाषा में नागरिक समस्याएं रिपोर्ट करें। AI स्वचालित रूप से उन्हें सही विभाग को वर्गीकृत और भेजता है।',
    reportAnIssue: 'समस्या रिपोर्ट करें',
    viewComplaintsMap: 'शिकायत मानचित्र देखें',
    issuesReported: 'रिपोर्ट की गई समस्याएं',
    resolved: 'हल की गई',
    cities: 'शहर',
    languages: 'भाषाएं',
    citizenPortal: 'नागरिक पोर्टल',
    citizenPortalDesc: 'समस्याएं रिपोर्ट करें, स्थिति ट्रैक करें, शिकायतों पर वोट करें।',
    enterPortal: 'पोर्टल में जाएं',
    officerDashboard: 'अधिकारी डैशबोर्ड',
    officerDashboardDesc: 'असाइन की गई शिकायतें देखें, स्थिति अपडेट करें।',
    officerLogin: 'अधिकारी लॉगिन',
    adminPanel: 'व्यवस्थापक पैनल',
    adminPanelDesc: 'विभाग, अधिकारी, SLA प्रबंधित करें और विश्लेषण देखें।',
    adminLogin: 'व्यवस्थापक लॉगिन',
    poweredByAI: 'AI द्वारा संचालित। नागरिकों के लिए डिज़ाइन।',
    voiceReporting: 'आवाज़ रिपोर्टिंग',
    voiceReportingDesc: 'किसी भी भाषा में आवाज़ से समस्या रिपोर्ट करें',
    interactiveMap: 'इंटरैक्टिव मानचित्र',
    interactiveMapDesc: 'लाइव मानचित्र पर सभी शिकायतें देखें',
    aiClassification: 'AI वर्गीकरण',
    aiClassificationDesc: 'सही विभाग को स्वचालित रूटिंग',
    duplicateDetection: 'डुप्लीकेट पहचान',
    duplicateDetectionDesc: 'स्मार्ट पहचान दोहराव रिपोर्ट रोकती है',
    realTimeTracking: 'वास्तविक समय ट्रैकिंग',
    realTimeTrackingDesc: 'अपनी शिकायत की स्थिति लाइव ट्रैक करें',
    anonymousMode: 'गुमनाम मोड',
    anonymousModeDesc: 'अपनी पहचान छुपाकर रिपोर्ट करें',
    footerText: '© 2025 CivicVoice — AI-आधारित बहुभाषी नागरिक समस्या रिपोर्टिंग प्लेटफ़ॉर्म',

    // Citizen Dashboard
    welcomeBack: 'स्वागत है',
    trackManage: 'अपने क्षेत्र की नागरिक समस्याएं ट्रैक और प्रबंधित करें',
    totalIssues: 'कुल समस्याएं',
    pending: 'लंबित',
    inProgress: 'प्रगति में',
    resolvedStat: 'हल हुई',
    newReport: 'नई रिपोर्ट',
    voiceReport: 'आवाज़ रिपोर्ट',
    nearbyIssues: 'पास की समस्याएं',
    recentComplaints: 'हाल की शिकायतें',
    all: 'सभी',
    loadingComplaints: 'शिकायतें लोड हो रही हैं...',
    noComplaintsFound: 'कोई शिकायत नहीं मिली',
    beFirstToReport: 'पहली समस्या रिपोर्ट करें →',

    // Report Issue
    reportACivicIssue: 'नागरिक समस्या रिपोर्ट करें',
    helpImprove: 'समस्याएं रिपोर्ट करके अपने समुदाय को बेहतर बनाएं',
    issueDetails: 'समस्या का विवरण',
    issueTitle: 'समस्या का शीर्षक',
    issueTitlePlaceholder: 'जैसे, मुख्य सड़क पर बड़ा गड्ढा',
    description: 'विवरण',
    descriptionPlaceholder: 'समस्या का विस्तार से वर्णन करें। आप अपनी भाषा में आवाज़ इनपुट भी उपयोग कर सकते हैं।',
    severityLevel: 'गंभीरता स्तर',
    language: 'भाषा',
    reportAnonymously: 'गुमनाम रिपोर्ट करें',
    reportAnonymouslyDesc: '— आपकी पहचान सार्वजनिक रूप से छुपी रहेगी',
    location: 'स्थान',
    locationDesc: 'समस्या का सटीक स्थान पिन करने के लिए मानचित्र पर क्लिक करें',
    uploadImages: 'छवियां अपलोड करें',
    clickToUpload: 'फोटो अपलोड करने के लिए क्लिक करें',
    uploadFormats: 'JPG, PNG अधिकतम 10MB',
    submitReport: '📤 रिपोर्ट सबमिट करें',
    submitting: 'सबमिट हो रहा है...',
    cancel: 'रद्द करें',
    stop: 'रोकें',
    voiceInput: 'आवाज़ इनपुट',
    listening: 'सुन रहे हैं... अभी बोलें',

    // Map
    complaintsMap: 'शिकायत मानचित्र',
    filterByStatus: 'स्थिति से फ़िल्टर करें',
    colorBy: 'रंग के अनुसार',
    category: 'श्रेणी',
    status: 'स्थिति',
    show1kmRadius: '1km त्रिज्या दिखाएं',
    legend: 'संकेत',
    complaintsShown: 'शिकायतें दिख रही हैं',
    recentIssues: 'हाल की समस्याएं',
    loadingMap: 'मानचित्र लोड हो रहा है...',
    signInToReport: 'रिपोर्ट के लिए साइन इन करें',

    // Complaint Detail
    complaintDetails: 'शिकायत विवरण',
    back: '← वापस',
    support: 'समर्थन',
    readAloud: '🔊 जोर से पढ़ें',
    readAloudStop: '⏹️ रोकें',
    issuePhotos: 'समस्या की तस्वीरें',
    resolutionNote: '✅ समाधान नोट',
    resolvedOn: 'हल हुई तारीख',
    locationLabel: '📍 स्थान',
    statusTimeline: 'स्थिति समयरेखा',
    assignedOfficer: 'असाइन अधिकारी',
    issueInfo: 'समस्या जानकारी',
    reportedBy: 'रिपोर्ट किया',
    priority: 'प्राथमिकता',
    reportedOn: 'रिपोर्ट की तारीख',
    slaDeadline: 'SLA समयसीमा',
    naLabel: 'N/A',
    anonymous: 'गुमनाम',
    yes: 'हाँ',
    no: 'नहीं',
    severity: 'गंभीरता',
    votes: 'वोट',
    department: 'विभाग',
    complaintNotFound: 'शिकायत नहीं मिली',
    backToDashboard: 'डैशबोर्ड पर वापस',

    // Officer Dashboard
    officerDashboardTitle: 'अधिकारी डैशबोर्ड',
    assignedComplaints: 'असाइन शिकायतें',
    totalAssigned: 'कुल असाइन',
    update: 'अपडेट',
    updateComplaint: 'शिकायत अपडेट',
    updateStatus: 'स्थिति अपडेट करें',
    resolutionNoteLabel: 'समाधान नोट',
    resolutionNotePlaceholder: 'क्या कार्रवाई की गई बताएं...',
    resolutionImages: 'समाधान छवियां',
    uploadBeforeAfter: '📷 पहले/बाद की तस्वीरें अपलोड करें',
    updateStatusBtn: '✅ स्थिति अपडेट करें',
    updating: 'अपडेट हो रहा है...',
    noComplaintsAssigned: 'अभी तक कोई शिकायत असाइन नहीं',
    slaBreached: 'SLA उल्लंघन',
    hoursLeft: 'घंटे बचे',

    // Admin
    adminPanelTitle: 'व्यवस्थापक पैनल',
    manageEntire: 'पूरे CivicVoice प्लेटफ़ॉर्म का प्रबंधन करें',
    analytics: 'विश्लेषण',
    complaints: 'शिकायतें',
    officers: 'अधिकारी',
    departments: 'विभाग',
    citizens: 'नागरिक',
    slaRules: 'SLA नियम',
    totalComplaints: 'कुल शिकायतें',
    resolutionRate: 'समाधान दर',
    slaBreaches: 'SLA उल्लंघन',
    complaintsPassDeadline: 'समयसीमा पार शिकायतें',
    allOnTrack: 'सब ठीक है!',
    platformUsers: 'प्लेटफ़ॉर्म उपयोगकर्ता',
    categoryBreakdown: 'श्रेणी विश्लेषण',
    topOfficers: 'शीर्ष अधिकारी',
    noDataYet: 'अभी डेटा नहीं',
    addOfficer: '+ अधिकारी जोड़ें',
    addDepartment: '+ विभाग जोड़ें',
    seedDefaults: '🌱 डिफ़ॉल्ट सेट करें',
    deleteOfficer: 'इस अधिकारी को हटाएं?',
    allComplaints: 'सभी शिकायतें',
    assignLabel: 'असाइन करें...',
    title: 'शीर्षक',
    date: 'तारीख',
    assign: 'असाइन',
    name: 'नाम',
    email: 'ईमेल',
    joined: 'जुड़े',
    statusLabel: 'स्थिति',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    noCitizensYet: 'अभी कोई नागरिक पंजीकृत नहीं',
    noComplaintsYet: 'अभी कोई शिकायत नहीं',
    noOfficersYet: 'अभी कोई अधिकारी नहीं',
    noOfficersForDept: 'इस विभाग में कोई अधिकारी नहीं',
    addFirstOfficer: 'पहला अधिकारी जोड़ें',
    noDepartmentsYet: 'कोई विभाग कॉन्फ़िगर नहीं',
    seedDefaultDepartments: 'डिफ़ॉल्ट विभाग सेट करें',
    addNewOfficer: 'नया अधिकारी जोड़ें',
    fullName: 'पूरा नाम',
    password: 'पासवर्ड',
    selectDepartment: 'विभाग चुनें',
    jurisdictionArea: 'क्षेत्राधिकार / क्षेत्र',
    adding: 'जोड़ा जा रहा है...',
    departmentName: 'विभाग का नाम',
    departmentDescription: 'विवरण',
    keywords: 'कीवर्ड (अल्पविराम से अलग)',
    highSLA: 'उच्च SLA (घंटे)',
    mediumSLA: 'मध्यम SLA (घंटे)',
    lowSLA: 'निम्न SLA (घंटे)',

    // SLA Rules
    slaRulesTitle: 'SLA नियम',
    slaRulesDesc: 'विभाग, श्रेणी और प्राथमिकता के अनुसार समयसीमा निर्धारित करें',
    addSlaRule: '+ SLA नियम जोड़ें',
    editSlaRule: 'SLA नियम संपादित करें',
    selectCategory: 'श्रेणी चुनें',
    selectPriority: 'प्राथमिकता चुनें',
    deadlineHours: 'समयसीमा (घंटे)',
    saveSlaRule: 'नियम सहेजें',
    saving: 'सहेजा जा रहा है...',
    noSlaRules: 'अभी कोई SLA नियम नहीं',
    hours: 'घंटे',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'निम्न',

    // Auth
    citizenLogin: 'नागरिक लॉगिन',
    citizenRegister: 'पंजीकरण',
    officerLoginTitle: 'अधिकारी लॉगिन',
    adminLoginTitle: 'व्यवस्थापक लॉगिन',
    emailAddress: 'ईमेल पता',
    enterPassword: 'पासवर्ड',
    signingIn: 'साइन इन हो रहा है...',
    registering: 'पंजीकरण हो रहा है...',
    alreadyHaveAccount: 'पहले से खाता है?',
    dontHaveAccount: 'खाता नहीं है?',
    createAccount: 'खाता बनाएं',

    // Auth page — extended
    welcomeBackCitizen: 'वापस स्वागत है',
    citizenLoginSubtitle: 'नागरिक समस्याएं रिपोर्ट करने और ट्रैक करने के लिए साइन इन करें',
    officerPortalTitle: 'अधिकारी पोर्टल',
    officerLoginSubtitle: 'नागरिक शिकायतों को प्रबंधित करने और हल करने के लिए साइन इन करें',
    adminPortalTitle: 'व्यवस्थापक पैनल',
    adminLoginSubtitle: 'सिस्टम प्रशासन और विश्लेषण',
    createAccountTitle: 'खाता बनाएं',
    citizenRegisterSubtitle: 'हजारों लोगों के साथ अपने शहर को बेहतर बनाएं',
    fullName: 'पूरा नाम',
    fullNamePlaceholder: 'राम कुमार',
    emailPlaceholder: 'aap@example.com',
    officerEmailLabel: 'अधिकारी ईमेल',
    officerEmailPlaceholder: 'adhikari@nagar.gov.in',
    adminEmailLabel: 'व्यवस्थापक ईमेल',
    adminEmailPlaceholder: 'admin@nagar.gov.in',
    passwordPlaceholder: '••••••••',
    atLeast6Chars: 'कम से कम 6 अक्षर',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    signInBtn: 'साइन इन करें',
    signInAsOfficer: 'अधिकारी के रूप में साइन इन करें',
    signInAsAdmin: 'व्यवस्थापक के रूप में साइन इन करें',
    registerHere: 'यहां पंजीकरण करें',
    signInLink: 'साइन इन करें',
    creatingAccount: 'खाता बन रहा है...',
    officerAdminPortal: 'क्या आप अधिकारी या व्यवस्थापक हैं?',
    backToHome: '← होम पर वापस',
    demoCredentials: 'डेमो',
    passwordsMismatch: 'पासवर्ड मेल नहीं खाते',
    passwordTooShort: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    citizenPortalOnly: 'यह पोर्टल केवल नागरिकों के लिए है।',
    officerPortalOnly: 'यह पोर्टल केवल अधिकारियों के लिए है।',
    adminPortalOnly: 'यह पोर्टल केवल व्यवस्थापकों के लिए है।',
    loginFailed: 'लॉगिन विफल',
    registrationFailed: 'पंजीकरण विफल',
    deptName: 'विभाग का नाम',
    deptDescription: 'विवरण',
    maxHours: 'अधिकतम घंटे',
    noDescription: 'कोई विवरण नहीं',
    seedDepartments: '🌱 विभाग जोड़ें',

    // Duplicate modal
    similarIssueFound: 'समान समस्या मिली!',
    similarIssueDesc: 'यह समस्या पास में पहले से मौजूद है। क्या आप इसे समर्थन देना चाहेंगे?',
    supportThisIssue: '👍 इस समस्या का समर्थन करें',
    reportAnyway: 'फिर भी रिपोर्ट करें',
  },

  te: {
    // Navbar
    dashboard: 'డాష్‌బోర్డ్',
    reportIssue: 'సమస్య నివేదించు',
    mapView: 'మ్యాప్ వ్యూ',
    logout: 'లాగ్ అవుట్',
    signIn: 'సైన్ ఇన్',
    citizen: 'పౌరుడు',
    officer: 'అధికారి',
    admin: 'నిర్వాహకుడు',

    // Landing
    heroTag: 'AI-శక్తితో · బహుభాషా · రియల్-టైమ్',
    heroTitle1: 'మీ నగరం.',
    heroTitle2: 'మీ గొంతు.',
    heroTitle3: 'నిజమైన చర్య.',
    heroDesc: 'మీ భాషలో పౌర సమస్యలను నివేదించండి. AI స్వయంచాలకంగా వాటిని సరైన విభాగానికి పంపిస్తుంది.',
    reportAnIssue: 'సమస్య నివేదించు',
    viewComplaintsMap: 'ఫిర్యాదుల మ్యాప్ చూడు',
    issuesReported: 'నివేదించిన సమస్యలు',
    resolved: 'పరిష్కరించబడినవి',
    cities: 'నగరాలు',
    languages: 'భాషలు',
    citizenPortal: 'పౌర పోర్టల్',
    citizenPortalDesc: 'సమస్యలు నివేదించండి, స్థితిని ట్రాక్ చేయండి, ఫిర్యాదులపై ఓటు వేయండి.',
    enterPortal: 'పోర్టల్ లోపలికి',
    officerDashboard: 'అధికారి డాష్‌బోర్డ్',
    officerDashboardDesc: 'కేటాయించిన ఫిర్యాదులు చూడండి, స్థితిని నవీకరించండి.',
    officerLogin: 'అధికారి లాగిన్',
    adminPanel: 'నిర్వాహక పేనల్',
    adminPanelDesc: 'విభాగాలు, అధికారులు, SLA నిర్వహించండి మరియు విశ్లేషణలు చూడండి.',
    adminLogin: 'నిర్వాహక లాగిన్',
    poweredByAI: 'AI తో శక్తివంతమైనది. పౌరుల కోసం రూపొందించబడింది.',
    voiceReporting: 'వాయిస్ రిపోర్టింగ్',
    voiceReportingDesc: 'ఏ భాషలోనైనా మీ గొంతుతో సమస్యలు నివేదించండి',
    interactiveMap: 'ఇంటరాక్టివ్ మ్యాప్',
    interactiveMapDesc: 'లైవ్ మ్యాప్‌లో అన్ని ఫిర్యాదులు చూడండి',
    aiClassification: 'AI వర్గీకరణ',
    aiClassificationDesc: 'సరైన విభాగానికి స్వయంచాలక రూటింగ్',
    duplicateDetection: 'డూప్లికేట్ గుర్తింపు',
    duplicateDetectionDesc: 'స్మార్ట్ గుర్తింపు పునరావృత నివేదికలను నిరోధిస్తుంది',
    realTimeTracking: 'రియల్-టైమ్ ట్రాకింగ్',
    realTimeTrackingDesc: 'మీ ఫిర్యాదు స్థితిని లైవ్‌లో ట్రాక్ చేయండి',
    anonymousMode: 'అనామక మోడ్',
    anonymousModeDesc: 'మీ గుర్తింపు వెల్లడించకుండా నివేదించండి',
    footerText: '© 2025 CivicVoice — AI-ఆధారిత బహుభాషా పౌర సమస్య నివేదన వేదిక',

    // Citizen Dashboard
    welcomeBack: 'స్వాగతం',
    trackManage: 'మీ ప్రాంతంలో పౌర సమస్యలను ట్రాక్ మరియు నిర్వహించండి',
    totalIssues: 'మొత్తం సమస్యలు',
    pending: 'పెండింగ్',
    inProgress: 'పురోగతిలో',
    resolvedStat: 'పరిష్కరించబడింది',
    newReport: 'కొత్త నివేదిక',
    voiceReport: 'వాయిస్ నివేదిక',
    nearbyIssues: 'సమీప సమస్యలు',
    recentComplaints: 'ఇటీవలి ఫిర్యాదులు',
    all: 'అన్నీ',
    loadingComplaints: 'ఫిర్యాదులు లోడ్ అవుతున్నాయి...',
    noComplaintsFound: 'ఫిర్యాదులు కనుగొనబడలేదు',
    beFirstToReport: 'మొదటి సమస్యను నివేదించండి →',

    // Report Issue
    reportACivicIssue: 'పౌర సమస్య నివేదించు',
    helpImprove: 'సమస్యలు నివేదించడం ద్వారా మీ సమాజాన్ని మెరుగుపరచండి',
    issueDetails: 'సమస్య వివరాలు',
    issueTitle: 'సమస్య శీర్షిక',
    issueTitlePlaceholder: 'ఉదా., మెయిన్ స్ట్రీట్‌లో పెద్ద గుంత',
    description: 'వివరణ',
    descriptionPlaceholder: 'సమస్యను వివరంగా వర్ణించండి. మీరు మీ భాషలో వాయిస్ ఇన్‌పుట్ కూడా ఉపయోగించవచ్చు.',
    severityLevel: 'తీవ్రత స్థాయి',
    language: 'భాష',
    reportAnonymously: 'అనామకంగా నివేదించు',
    reportAnonymouslyDesc: '— మీ గుర్తింపు బహిరంగంగా దాచబడుతుంది',
    location: 'స్థానం',
    locationDesc: 'సమస్య యొక్క ఖచ్చితమైన స్థానాన్ని పిన్ చేయడానికి మ్యాప్‌పై క్లిక్ చేయండి',
    uploadImages: 'చిత్రాలు అప్‌లోడ్ చేయండి',
    clickToUpload: 'ఫోటోలు అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి',
    uploadFormats: 'JPG, PNG గరిష్టంగా 10MB',
    submitReport: '📤 నివేదిక సమర్పించు',
    submitting: 'సమర్పిస్తోంది...',
    cancel: 'రద్దు చేయండి',
    stop: 'ఆపు',
    voiceInput: 'వాయిస్ ఇన్‌పుట్',
    listening: 'వింటున్నాను... ఇప్పుడు మాట్లాడండి',

    // Map
    complaintsMap: 'ఫిర్యాదుల మ్యాప్',
    filterByStatus: 'స్థితి ద్వారా ఫిల్టర్ చేయండి',
    colorBy: 'రంగు వర్గీకరణ',
    category: 'వర్గం',
    status: 'స్థితి',
    show1kmRadius: '1km వ్యాసార్థం చూపించు',
    legend: 'సంకేతం',
    complaintsShown: 'ఫిర్యాదులు చూపబడుతున్నాయి',
    recentIssues: 'ఇటీవలి సమస్యలు',
    loadingMap: 'మ్యాప్ లోడ్ అవుతోంది...',
    signInToReport: 'నివేదించడానికి సైన్ ఇన్ చేయండి',

    // Complaint Detail
    complaintDetails: 'ఫిర్యాదు వివరాలు',
    back: '← వెనక్కి',
    support: 'మద్దతు',
    readAloud: '🔊 బిగ్గరగా చదవు',
    readAloudStop: '⏹️ ఆపు',
    issuePhotos: 'సమస్య ఫోటోలు',
    resolutionNote: '✅ పరిష్కార నోట్',
    resolvedOn: 'పరిష్కరించబడిన తేదీ',
    locationLabel: '📍 స్థానం',
    statusTimeline: 'స్థితి టైమ్‌లైన్',
    assignedOfficer: 'కేటాయించిన అధికారి',
    issueInfo: 'సమస్య సమాచారం',
    reportedBy: 'నివేదించిన వారు',
    priority: 'ప్రాధాన్యత',
    reportedOn: 'నివేదించిన తేదీ',
    slaDeadline: 'SLA గడువు',
    naLabel: 'వర్తించదు',
    anonymous: 'అనామక',
    yes: 'అవును',
    no: 'కాదు',
    severity: 'తీవ్రత',
    votes: 'ఓట్లు',
    department: 'విభాగం',
    complaintNotFound: 'ఫిర్యాదు కనుగొనబడలేదు',
    backToDashboard: 'డాష్‌బోర్డ్‌కు వెనక్కి',

    // Officer Dashboard
    officerDashboardTitle: 'అధికారి డాష్‌బోర్డ్',
    assignedComplaints: 'కేటాయించిన ఫిర్యాదులు',
    totalAssigned: 'మొత్తం కేటాయించబడినవి',
    update: 'నవీకరించు',
    updateComplaint: 'ఫిర్యాదు నవీకరించు',
    updateStatus: 'స్థితి నవీకరించు',
    resolutionNoteLabel: 'పరిష్కార నోట్',
    resolutionNotePlaceholder: 'ఏ చర్య తీసుకోబడింది వివరించండి...',
    resolutionImages: 'పరిష్కార చిత్రాలు',
    uploadBeforeAfter: '📷 ముందు/తర్వాత ఫోటోలు అప్‌లోడ్ చేయండి',
    updateStatusBtn: '✅ స్థితి నవీకరించు',
    updating: 'నవీకరిస్తోంది...',
    noComplaintsAssigned: 'ఇంకా ఫిర్యాదులు కేటాయించబడలేదు',
    slaBreached: 'SLA ఉల్లంఘన',
    hoursLeft: 'గంటలు మిగిలాయి',

    // Admin
    adminPanelTitle: 'నిర్వాహక పేనల్',
    manageEntire: 'మొత్తం CivicVoice వేదికను నిర్వహించండి',
    analytics: 'విశ్లేషణలు',
    complaints: 'ఫిర్యాదులు',
    officers: 'అధికారులు',
    departments: 'విభాగాలు',
    citizens: 'పౌరులు',
    slaRules: 'SLA నియమాలు',
    totalComplaints: 'మొత్తం ఫిర్యాదులు',
    resolutionRate: 'పరిష్కార రేటు',
    slaBreaches: 'SLA ఉల్లంఘనలు',
    complaintsPassDeadline: 'గడువు దాటిన ఫిర్యాదులు',
    allOnTrack: 'అన్నీ సరిగ్గా ఉన్నాయి!',
    platformUsers: 'వేదిక వినియోగదారులు',
    categoryBreakdown: 'వర్గం విశ్లేషణ',
    topOfficers: 'అగ్ర అధికారులు',
    noDataYet: 'ఇంకా డేటా లేదు',
    addOfficer: '+ అధికారిని జోడించు',
    addDepartment: '+ విభాగం జోడించు',
    seedDefaults: '🌱 డిఫాల్ట్‌లు సెట్ చేయి',
    deleteOfficer: 'ఈ అధికారిని తొలగించాలా?',
    allComplaints: 'అన్ని ఫిర్యాదులు',
    assignLabel: 'కేటాయించు...',
    title: 'శీర్షిక',
    date: 'తేదీ',
    assign: 'కేటాయించు',
    name: 'పేరు',
    email: 'ఇమెయిల్',
    joined: 'చేరారు',
    statusLabel: 'స్థితి',
    active: 'చురుకుగా',
    inactive: 'నిష్క్రియంగా',
    noCitizensYet: 'ఇంకా పౌరులు నమోదు కాలేదు',
    noComplaintsYet: 'ఇంకా ఫిర్యాదులు లేవు',
    noOfficersYet: 'ఇంకా అధికారులు జోడించబడలేదు',
    noOfficersForDept: 'ఈ విభాగంలో అధికారులు లేరు',
    addFirstOfficer: 'మొదటి అధికారిని జోడించు',
    noDepartmentsYet: 'విభాగాలు కాన్ఫిగర్ కాలేదు',
    seedDefaultDepartments: 'డిఫాల్ట్ విభాగాలు సెట్ చేయి',
    addNewOfficer: 'కొత్త అధికారిని జోడించు',
    fullName: 'పూర్తి పేరు',
    password: 'పాస్‌వర్డ్',
    selectDepartment: 'విభాగాన్ని ఎంచుకోండి',
    jurisdictionArea: 'అధికార పరిధి / ప్రాంతం',
    adding: 'జోడిస్తోంది...',
    departmentName: 'విభాగం పేరు',
    departmentDescription: 'వివరణ',
    keywords: 'కీవర్డ్‌లు (కామాతో వేరు చేయండి)',
    highSLA: 'అధిక SLA (గంటలు)',
    mediumSLA: 'మధ్యస్థ SLA (గంటలు)',
    lowSLA: 'తక్కువ SLA (గంటలు)',

    // SLA Rules
    slaRulesTitle: 'SLA నియమాలు',
    slaRulesDesc: 'విభాగం, వర్గం మరియు ప్రాధాన్యత ద్వారా గడువులు నిర్ణయించండి',
    addSlaRule: '+ SLA నియమం జోడించు',
    editSlaRule: 'SLA నియమాన్ని సవరించు',
    selectCategory: 'వర్గాన్ని ఎంచుకోండి',
    selectPriority: 'ప్రాధాన్యతను ఎంచుకోండి',
    deadlineHours: 'గడువు (గంటలు)',
    saveSlaRule: 'నియమం సేవ్ చేయండి',
    saving: 'సేవ్ అవుతోంది...',
    noSlaRules: 'ఇంకా SLA నియమాలు లేవు',
    hours: 'గంటలు',
    high: 'అధికం',
    medium: 'మధ్యస్థం',
    low: 'తక్కువ',

    // Auth
    citizenLogin: 'పౌర లాగిన్',
    citizenRegister: 'నమోదు',
    officerLoginTitle: 'అధికారి లాగిన్',
    adminLoginTitle: 'నిర్వాహక లాగిన్',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    enterPassword: 'పాస్‌వర్డ్',
    signingIn: 'సైన్ ఇన్ అవుతోంది...',
    registering: 'నమోదు అవుతోంది...',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    dontHaveAccount: 'ఖాతా లేదా?',
    createAccount: 'ఖాతా సృష్టించు',

    // Auth page — extended
    welcomeBackCitizen: 'తిరిగి స్వాగతం',
    citizenLoginSubtitle: 'పౌర సమస్యలు నివేదించడానికి మరియు ట్రాక్ చేయడానికి సైన్ ఇన్ చేయండి',
    officerPortalTitle: 'అధికారి పోర్టల్',
    officerLoginSubtitle: 'పౌర ఫిర్యాదులను నిర్వహించడానికి మరియు పరిష్కరించడానికి సైన్ ఇన్ చేయండి',
    adminPortalTitle: 'నిర్వాహక ప్యానెల్',
    adminLoginSubtitle: 'సిస్టమ్ నిర్వహణ మరియు విశ్లేషణలు',
    createAccountTitle: 'ఖాతా సృష్టించు',
    citizenRegisterSubtitle: 'మీ నగరాన్ని మెరుగుపరచడంలో వేలాది మందిలో చేరండి',
    fullName: 'పూర్తి పేరు',
    fullNamePlaceholder: 'రాము కుమార్',
    emailPlaceholder: 'మీరు@example.com',
    officerEmailLabel: 'అధికారి ఇమెయిల్',
    officerEmailPlaceholder: 'adhikari@municipality.gov',
    adminEmailLabel: 'నిర్వాహక ఇమెయిల్',
    adminEmailPlaceholder: 'admin@municipality.gov',
    passwordPlaceholder: '••••••••',
    atLeast6Chars: 'కనీసం 6 అక్షరాలు',
    confirmPassword: 'పాస్‌వర్డ్ నిర్ధారించండి',
    signInBtn: 'సైన్ ఇన్ చేయండి',
    signInAsOfficer: 'అధికారిగా సైన్ ఇన్ చేయండి',
    signInAsAdmin: 'నిర్వాహకుడిగా సైన్ ఇన్ చేయండి',
    registerHere: 'ఇక్కడ నమోదు చేయండి',
    signInLink: 'సైన్ ఇన్ చేయండి',
    creatingAccount: 'ఖాతా సృష్టిస్తోంది...',
    officerAdminPortal: 'మీరు అధికారి లేదా నిర్వాహకుడా?',
    backToHome: '← హోమ్‌కు తిరిగి',
    demoCredentials: 'డెమో',
    passwordsMismatch: 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు',
    passwordTooShort: 'పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి',
    citizenPortalOnly: 'ఈ పోర్టల్ పౌరులకు మాత్రమే.',
    officerPortalOnly: 'ఈ పోర్టల్ అధికారులకు మాత్రమే.',
    adminPortalOnly: 'ఈ పోర్టల్ నిర్వాహకులకు మాత్రమే.',
    loginFailed: 'లాగిన్ విఫలమైంది',
    registrationFailed: 'నమోదు విఫలమైంది',
    deptName: 'విభాగం పేరు',
    deptDescription: 'వివరణ',
    maxHours: 'గరిష్ట గంటలు',
    noDescription: 'వివరణ లేదు',
    seedDepartments: '🌱 విభాగాలు జోడించు',

    // Duplicate modal
    similarIssueFound: 'సమాన సమస్య కనుగొనబడింది!',
    similarIssueDesc: 'ఈ సమస్య సమీపంలో ఇప్పటికే ఉంది. దాన్ని మద్దతు ఇవ్వాలనుకుంటున్నారా?',
    supportThisIssue: '👍 ఈ సమస్యకు మద్దతు ఇవ్వు',
    reportAnyway: 'అయినా నివేదించు',
  }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('civic_lang') || 'en');

  useEffect(() => {
    localStorage.setItem('civic_lang', lang);
  }, [lang]);

  const t = (key) => translations[lang]?.[key] || translations['en']?.[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
};

export default LanguageContext;
